name: ScholarAI

services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9092
      
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,CONTROLLER://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9094,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # Other settings
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app-network
  
  minio:
    image: 'minio/minio:latest'
    platform: linux/amd64
    ports:
      - '9000:9000'  # S3 API port
      - '9001:9001'  # MinIO Console Web UI port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network
    volumes:
      - minio-data:/data
    
  postgresql:
    image: pgvector/pgvector:pg17
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: scholar_ai
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d scholar_ai"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
    driver: local
  pgdata:
    driver: local