"""Create research_jobs table

Revision ID: 15c585b2ff05
Revises: 4e8c20ca146f
Create Date: 2025-07-08 11:03:17.575086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c585b2ff05'
down_revision: Union[str, Sequence[str], None] = '4e8c20ca146f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PODCAST_PENDING', 'PODCAST_COMPLETED', name='jobstatus'), nullable=False),
    sa.Column('research_topic', sa.Text(), nullable=False),
    sa.Column('source_video_url', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('report_url', sa.String(), nullable=True),
    sa.Column('podcast_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_jobs_user_id'), 'research_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_jobs_user_id'), table_name='research_jobs')
    op.drop_table('research_jobs')
    # ### end Alembic commands ###
