"""Add failure_reason to research_jobs

Revision ID: e2b8bcec1480
Revises: 384ed2cf21df
Create Date: 2025-07-18 18:12:15.757774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b8bcec1480'
down_revision: Union[str, Sequence[str], None] = '384ed2cf21df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_jobs', sa.Column('failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_jobs', 'failure_reason')
    # ### end Alembic commands ###
